import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "../styles/Home.module.css";
import { Container } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
import CountryCurrencyFlags from "../components/Header/CountryCurrencyFlags";
import DealsAndHighlights from "@/components/DealsAndHighlights/DealsAndHighlights";
import Stories from "@/components/Stories/Stories";
import Affiliation from "@/components/Affiliation/Affiliation";
import {Hidden} from "@mui/material"
import Footer from "../components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const theme = useTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero />
        <DealsAndHighlights />
        <Stories />
        <Hidden smDown>
        <Affiliation />
        </Hidden>
        <Footer />
      </main>
    </>
  );
}
